twostepauth/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User, SiteProfileNotAvailable
from django.contrib.auth.tokens import default_token_generator
from django.contrib.admin.forms import AdminAuthenticationForm
from django.db.models import get_model
from django.utils.translation import ugettext_lazy as _
from . import settings as twostepauth_settings
from .auth_backend import TwoStepAuthBackend

#from django-profiles
def get_profile_model():
    """
    Return the model class for the currently-active user profile
    model, as defined by the ``AUTH_PROFILE_MODULE`` setting. If that
    setting is missing, raise
    ``django.contrib.auth.models.SiteProfileNotAvailable``.

    """
    if (not hasattr(settings, 'AUTH_PROFILE_MODULE')) or \
           (not settings.AUTH_PROFILE_MODULE):
        raise SiteProfileNotAvailable
    profile_mod = get_model(*settings.AUTH_PROFILE_MODULE.split('.'))
    if profile_mod is None:
        raise SiteProfileNotAvailable
    return profile_mod


def get_profile_form():
    """
    Returns a profile model form without the two-step authentication fields
    """
    profile_mod = get_profile_model()
    class _ProfileForm(forms.ModelForm):
        class Meta:
            model = profile_mod
            exclude = ('user', 'tsa_active', 'tsa_secret', 'tsa_backup_codes', 
                       'tsa_hotp_counter', 'tsa_skew')
    return _ProfileForm


TWOSTEPAUTH_METHOD_OPTIONS = (
    ('APP', 'Mobile App'),
    ('BACKUP', 'Backup codes'),
)


class TwoStepAuthenticationForm(AuthenticationForm):
    """
    Form for the first step of login in the two-step authentication process.
    """
    def __init__(self, *args, **kw):
        if kw.has_key('remember_token'):
            self.remember_token = kw['remember_token']
            del kw['remember_token']
        else:
            self.remember_token = None
        self.user = None
        self.usertoken = None
        super(TwoStepAuthenticationForm, self).__init__(*args, **kw)

    def clean(self):
        """
        Checks for the username and password.

        If the user cannot be authenticated tries to generate the user token 
        for the second step of the authentication process. If the token cannot 
        be generated a validation error is raised.

        If the user is not active a validation error is raised.
        """
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            force_single_step = not twostepauth_settings.TWOSTEPAUTH_FOR_USERS
            self.user = authenticate(username=username, password=password, 
                            remember_token=self.remember_token, 
                            force_single_step=force_single_step)
            if self.user is None:
                # see if this guy has two-step auth enabled
                self.usertoken = TwoStepAuthBackend().first_step(
                                        username=username, password=password)
                if self.usertoken is None:
                    raise forms.ValidationError(_("Please enter a correct username and password. Note that both fields are case-sensitive."))
            elif not self.user.is_active:
                raise forms.ValidationError(_("This account is inactive."))
        self.check_for_test_cookie()
        return self.cleaned_data

    def get_user(self):
        """
        Returns the authenticated user object if authentication was done, 
        otherwise it will be None
        """
        return self.user


class TokenAuthenticationForm(forms.Form):
    """
    Form for the second step of login in the two-step authentication process
    where the application code or backup codes are entered to complete the
    authentication.
    """
    code = forms.IntegerField(label=_("Authentication Code"),
        help_text=_(u"If you have enabled two-factor authentication, enter the "
            "six-digit number from your authentication device here."),
        widget=forms.TextInput(attrs={'maxlength':'8'}),
        min_value=0, max_value=99999999,
        required=True
    )
    method = forms.CharField(label=_("Authentication method"),
                             widget=forms.Select(choices = TWOSTEPAUTH_METHOD_OPTIONS),
                             required = True,
                            )
    remember_computer = forms.BooleanField(widget=forms.CheckboxInput(),
                               required=False,
                               initial=False,
                               label=_(u'Remember this computer for %(days)s days') % {'days': twostepauth_settings.TWOSTEPAUTH_REMEMBER_COMPUTER_DAYS})
    authkey = forms.CharField(widget=forms.HiddenInput())
    username = forms.CharField(widget=forms.HiddenInput())
    remember = forms.BooleanField(widget=forms.HiddenInput(), required=False)

    def clean(self):
        code = self.cleaned_data.get('code')
        method = self.cleaned_data.get('method')
        username = self.cleaned_data.get('username')
        authkey = self.cleaned_data.get('authkey')

        if method == 'APP' and code > 999999:
            raise forms.ValidationError(_(u"Wrong authentication code format"))

        self.user = authenticate(username=username, code=code, method=method, token=authkey)
        if not self.user:
            raise forms.ValidationError(_(u"User authentication failed"))
        
        return self.cleaned_data

    def get_user(self):
        """
        Returns the authenticated user object if authentication was done, 
        otherwise it will be None
        """
        return self.user


class TwoStepAuthEditForm(forms.Form):
    """
    Form for use in the user profile to activate/inactivate the use of two-step
    authentication.
    """
    tsa_active = forms.BooleanField(widget=forms.CheckboxInput(),
                                    required=False,
                                    label=_(u'Two-Step Authentication'))


class SingleStepAdminAuthenticationForm(AdminAuthenticationForm):
    """
    Form for authentication in the admin section of the site when the 
    two-step auth is disabled by the ``TWOSTEPAUTH_FOR_ADMIN`` setting.
    """
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        message = _("Please enter a correct username and password. "
                    "Note that username and password fields are case-sensitive.")
        if username and password:
            try:
                user = User.objects.get(username=username)
            except (User.DoesNotExist, User.MultipleObjectsReturned):
                raise forms.ValidationError(message)
            self.user_cache = authenticate(username=username, password=password, 
                                           force_single_step=True)
            if self.user_cache is None:
                raise forms.ValidationError(message)
            elif not self.user_cache.is_active or not self.user_cache.is_staff:
                raise forms.ValidationError(message)
        self.check_for_test_cookie()
        return self.cleaned_data


class TwoStepAdminAuthenticationForm(AdminAuthenticationForm):
    """
    Form forauthentication in the admin section of the site when the 
    two-step auth is enabled by the ``TWOSTEPAUTH_FOR_ADMIN`` setting.
    """
    code = forms.IntegerField(label=_("Authentication Code"),
        help_text=_(u"If you have enabled two-factor authentication, enter the "
            "six-digit number from your authentication device here."),
        widget=forms.TextInput(attrs={'maxlength':'8'}),
        min_value=0, max_value=99999999,
        required=False
    )
    method = forms.CharField(label=_("Authentication method"),
                             widget=forms.Select(choices = TWOSTEPAUTH_METHOD_OPTIONS),
                             required = True,
                            )
    remember_computer = forms.BooleanField(widget=forms.CheckboxInput(),
                               required=False,
                               initial=True,
                               label=_(u'Remember this computer for %(days)s days') % {
                                'days': twostepauth_settings.TWOSTEPAUTH_REMEMBER_COMPUTER_DAYS})

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        code = self.cleaned_data.get('code')
        method = self.cleaned_data.get('method')

        #app token codes have 6 digits
        if method == 'APP' and code > 999999:
            raise forms.ValidationError(_(u"Wrong authentication code format"))

        message = _("Please enter a correct username, password and token. "
                    "Note that username and password fields are case-sensitive.")
        
        if username and password:
            try:
                user = User.objects.get(username=username)
            except (User.DoesNotExist, User.MultipleObjectsReturned):
                raise forms.ValidationError(message)
            try:
                profile = user.get_profile()
            except:
                profile = None
            
            if profile and profile.tsa_active:
                self.user_cache = authenticate(username=username, password=password, 
                                               code=code, method=method)
            else:
                self.user_cache = authenticate(username=username, password=password)

            if self.user_cache is None:
                raise forms.ValidationError(message)
            elif not self.user_cache.is_active or not self.user_cache.is_staff:
                raise forms.ValidationError(message)
        self.check_for_test_cookie()
        

twostepauth/templates/twostepauth/adminlogin.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block extrastyle %}{% load staticfiles %} {{ block.super }}<link rel="stylesheet" type="text/css" href="{% static 'admin/css/login.css' %}" />{% endblock %}

{% block bodyclass %}login{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors and not form.this_is_the_login_form.errors %}
<p class="errornote">
{% blocktrans count form.errors.items|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
</p>
{% endif %}

{% if form.non_field_errors or form.this_is_the_login_form.errors %}
{% for error in form.non_field_errors|add:form.this_is_the_login_form.errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">
<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {% if not form.this_is_the_login_form.errors %}{{ form.username.errors }}{% endif %}
    <label for="id_username" class="required">{% trans 'Username:' %}</label> {{ form.username }}
  </div>
  <div class="form-row">
    {% if not form.this_is_the_login_form.errors %}{{ form.password.errors }}{% endif %}
    <label for="id_password" class="required">{% trans 'Password:' %}</label> {{ form.password }}
    <input type="hidden" name="this_is_the_login_form" value="1" />
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
  <div class="form-row">
    {% if not form.this_is_the_login_form.errors %}{{ form.code.errors }}{% endif %}
    <label for="id_code" class="required">{% trans 'Token code:' %}</label> {{ form.code }}
  </div>
  <div class="form-row">
    {% if not form.this_is_the_login_form.errors %}{{ form.method.errors }}{% endif %}
    <label for="id_method" class="required">{% trans 'Token method:' %}</label> {{ form.method }}
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endblock %}

twostepauth/templates/twostepauth/login.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'auth_login' %}">
{% csrf_token %}
<legend>Login</legend>
<label for="id_username">{{ form.username.label_tag }}</label>
{{ form.username }}
<br>
<label for="id_password">{{ form.password.label_tag }}</label>
{{ form.password }}
<br>
<div class="submit">
<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</div>		
</form>
{% endblock %}

twostepauth/templates/twostepauth/signin_token_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Signin Authentication Code" %}{% endblock %}

{% block content %}
<form action="{% url 'login_step_two' %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Authentication Code" %}</legend>
    {{ form.non_field_errors }}
    {% for field in form %}
    {% if field.is_hidden %}
    	{{ field }}
	{% else %}
		
    	<p>
    		{{ field.label_tag }}
    		{{ field }} 
			{% if field.errors %}<br>{{ field.errors }}{% endif %}
    	</p>
    {% endif %}
    {% endfor %}
  </fieldset>
  <div class="submit">
  <input type="submit" value="{% trans "Signin" %}" />
  {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
  </div>
</form>
{% endblock %}